apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tckhb-ingress-service
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: tckhb.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: tckhb-auth-clisterip-service
            port:
              number: 8001
  ingressClassName: nginx