FROM node:18-alpine

WORKDIR /app

ADD /package.json /app/package.json
RUN yarn install

ADD . /app

RUN yarn nx run orders:build --configuration=production 

CMD ["node","./dist/apps/orders/main.js"]