FROM node:16-alpine as build

WORKDIR /app

ADD package.json /app/package.json

RUN apk add --update python3 make g++ && rm -rf /var/cache/apk/*

RUN npm install -g nx
RUN npm install --legacy-peer-deps

ADD . /app

CMD ["nx", "serve", "auth"]