kubectl apply -f ./infra/k8s.prod/auth-mongo.deployment.yaml
kubectl apply -f ./infra/k8s.prod/ingress-service.yaml
kubectl apply -f ./infra/k8s.prod/expiration-redis.deployment.yaml
kubectl apply -f ./infra/k8s.prod/kafdrop.deployment.yaml
kubectl apply -f ./infra/k8s.prod/orders-mongo.deployment.yaml
kubectl apply -f ./infra/k8s.prod/kafka.deployment.yaml
kubectl apply -f ./infra/k8s.prod/payments-mongo.deployment.yaml
kubectl apply -f ./infra/k8s.prod/tickets-mongo.deployment.yaml
kubectl apply -f ./infra/k8s.prod/payments.deployment.yaml
kubectl apply -f ./infra/k8s.prod/auth.deployment.yaml
kubectl apply -f ./infra/k8s.prod/client.deployment.yaml
kubectl apply -f ./infra/k8s.prod/expiration.deployment.yaml
kubectl apply -f ./infra/k8s.prod/orders.deployment.yaml
kubectl apply -f ./infra/k8s.prod/tickets.deployment.yaml