apiVersion: apps/v1
kind: Deployment
metadata:
  name: tckhb-kafka-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tckhb-kafka
  template:
    metadata:
      labels:
        app: tckhb-kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          resources:
            limits:
              memory: '500Mi'
              cpu: '500m'
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://tckhb-kafka-clusterip-service:9092,EXTERNAL://minikubeip:30301
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: ALLOW_PLAINTEXT_LISTENER
              value: 'yes'
            - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
              value: 'true'
            - name: KAFKA_CFG_GROUP_COORDINATOR_NEW_ENABLE
              value: 'true'

---
apiVersion: v1
kind: Service
metadata:
  name: tckhb-kafka-clusterip-service
spec:
  selector:
    app: tckhb-kafka
  ports:
    - name: kafka-clusterip
      protocol: TCP
      port: 9092
      targetPort: 9092

---
apiVersion: v1
kind: Service
metadata:
  name: tckhb-kafka-nodeport-service
spec:
  type: NodePort
  selector:
    app: tckhb-kafka
  ports:
    - name: kafka-nodeport
      protocol: TCP
      port: 9094
      targetPort: 9094
      nodePort: 30301
